// ─────────────────────────────────────────────────────────────────────────────
//  Beam Studio — a tiny motion-graphics engine written from scratch.
//  Everything on screen (wood, rooms, type, icons) is generated by this code.
// ─────────────────────────────────────────────────────────────────────────────
const W = 1920, H = 1080, FPS = 30;
const TAU = Math.PI * 2;

// ── math ────────────────────────────────────────────────────────────────────
const clamp = (x, a = 0, b = 1) => Math.min(b, Math.max(a, x));
const lerp = (a, b, t) => a + (b - a) * t;
const inv = (a, b, x) => clamp((x - a) / (b - a));
const smooth = (a, b, x) => { const t = inv(a, b, x); return t * t * (3 - 2 * t); };
const E = {
  linear: t => t,
  inQuad: t => t * t,
  outQuad: t => 1 - (1 - t) * (1 - t),
  inCubic: t => t * t * t,
  outCubic: t => 1 - Math.pow(1 - t, 3),
  inOutCubic: t => t < .5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2,
  outQuint: t => 1 - Math.pow(1 - t, 5),
  inOutQuint: t => t < .5 ? 16 * t ** 5 : 1 - Math.pow(-2 * t + 2, 5) / 2,
  outExpo: t => t >= 1 ? 1 : 1 - Math.pow(2, -10 * t),
  inExpo: t => t <= 0 ? 0 : Math.pow(2, 10 * t - 10),
  inOutExpo: t => t <= 0 ? 0 : t >= 1 ? 1 : t < .5 ? Math.pow(2, 20 * t - 10) / 2 : (2 - Math.pow(2, -20 * t + 10)) / 2,
  inOutSine: t => -(Math.cos(Math.PI * t) - 1) / 2,
  outBack: t => { const s = 1.70158; return 1 + (s + 1) * Math.pow(t - 1, 3) + s * Math.pow(t - 1, 2); },
  outElastic: t => t <= 0 ? 0 : t >= 1 ? 1 : Math.pow(2, -10 * t) * Math.sin((t * 10 - .75) * TAU / 3) + 1,
};
// eased progress of a window [t0, t0+d]
const seg = (t, t0, d, e = E.outCubic) => e(clamp((t - t0) / d));
// in / hold / out envelope for elements living inside a shot
const env = (t, dur, a = .4, b = .4) => Math.min(inv(0, a, t), 1 - inv(dur - b, dur, t));

function rng(seed) {
  let s = seed >>> 0;
  return () => { s = (s + 0x6D2B79F5) >>> 0; let t = s; t = Math.imul(t ^ t >>> 15, t | 1); t ^= t + Math.imul(t ^ t >>> 7, t | 61); return ((t ^ t >>> 14) >>> 0) / 4294967296; };
}

// ── value noise + fbm ───────────────────────────────────────────────────────
function makeNoise(seed) {
  const r = rng(seed), P = new Uint16Array(512), V = new Float32Array(256);
  for (let i = 0; i < 256; i++) { P[i] = i; V[i] = r(); }
  for (let i = 255; i > 0; i--) { const j = (r() * (i + 1)) | 0; [P[i], P[j]] = [P[j], P[i]]; }
  for (let i = 0; i < 256; i++) P[i + 256] = P[i];
  const n = (x, y) => {
    const xi = Math.floor(x), yi = Math.floor(y), xf = x - xi, yf = y - yi;
    const X = xi & 255, Y = yi & 255;
    const u = xf * xf * (3 - 2 * xf), v = yf * yf * (3 - 2 * yf);
    const a = V[P[P[X] + Y]], b = V[P[P[X + 1] + Y]], c = V[P[P[X] + Y + 1]], d = V[P[P[X + 1] + Y + 1]];
    return a + (b - a) * u + (c - a) * v + (a - b - c + d) * u * v;
  };
  const fbm = (x, y, o = 4) => { let s = 0, a = .5, f = 1, t = 0; for (let i = 0; i < o; i++) { s += n(x * f, y * f) * a; t += a; a *= .5; f *= 2.03; } return s / t; };
  return { n, fbm };
}

// ── colour ──────────────────────────────────────────────────────────────────
const hex = h => [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)];
const rgba = (c, a = 1) => `rgba(${c[0] | 0},${c[1] | 0},${c[2] | 0},${a})`;
const mixc = (a, b, t) => [lerp(a[0], b[0], t), lerp(a[1], b[1], t), lerp(a[2], b[2], t)];

// brand lock: one accent, one warm neutral system
const C = {
  ink: '#15110d', ink2: '#221b15', cream: '#f4ecdf', paper: '#fbf7f0', muted: '#b9ab98',
  accent: '#d08a3c', accent2: '#f0b872', line: 'rgba(244,236,223,.18)',
};
const SANS = '"Liberation Sans", Arial, sans-serif';
const SERIF = '"Liberation Serif", Georgia, serif';
const font = (w, s, f = SANS) => `${w} ${s}px ${f}`;

// ── procedural wood ─────────────────────────────────────────────────────────
// A texture is generated once per style as a tone map + a relief (shade) map,
// then cheaply tinted for every finish.
const FINISHES = [
  { id: 'natural', name: 'Natural', light: '#d2ab76', dark: '#8d6033' },
  { id: 'honey', name: 'Honey Pecan', light: '#c08344', dark: '#6b3d1c' },
  { id: 'walnut', name: 'Walnut', light: '#8a5d3a', dark: '#3d2415' },
  { id: 'espresso', name: 'Espresso', light: '#5a3a27', dark: '#1f130b' },
  { id: 'gray', name: 'Weathered Gray', light: '#aaa396', dark: '#5b554c' },
  { id: 'primed', name: 'Primed White', light: '#f1ede5', dark: '#cfc8bb', flat: true },
];
// paint colours (not factory finishes) for the primed-and-painted demo
const PAINTS = [{ id: 'sage', name: 'Sage', light: '#96a48a', dark: '#7a876f', flat: true }];
const STYLES = [
  { id: 'hewn', name: 'Hand Hewn' },
  { id: 'sawn', name: 'Rough Sawn' },
  { id: 'blast', name: 'Sandblasted' },
  { id: 'smooth', name: 'Smooth' },
];

function woodMaps(style, w, h, seed, scale = 1) {
  const N = makeNoise(seed), N2 = makeNoise(seed + 991), R = rng(seed * 7 + 3);
  const tone = new Float32Array(w * h), ht = new Float32Array(w * h);
  const rings = (9 + R() * 4);
  const knots = [];
  for (let i = 0; i < Math.round(w * scale / 900) + 1; i++) knots.push({ x: R() * w, y: (.2 + R() * .6) * h, r: (10 + R() * 12) / scale, s: .5 + R() * .5 });
  for (let y = 0; y < h; y++) {
    const vy = y / h;
    for (let x = 0; x < w; x++) {
      const i = y * w + x, xs = x * scale, ys = y * scale;
      let d = ys / 240 * rings + N.fbm(xs * .0028, ys * .012, 3) * 1.6 + N.fbm(xs * .0005, ys * .003, 2) * 4;
      let kc = 0;
      for (const k of knots) { const dx = (x - k.x) / (k.r * 3.5), dy = (y - k.y) / k.r, dd = dx * dx + dy * dy; d += k.s * Math.exp(-dd * .6) * 2.2 * Math.sign(y - k.y || 1); kc += Math.exp(-dd * 5) * k.s; }
      const ring = d - Math.floor(d);
      const late = smooth(.55, .88, ring) * (1 - smooth(.9, 1, ring));
      const fib = N2.n(xs * .03, ys * .75) * .6 + N2.n(xs * .012, ys * 1.9) * .4;
      const pore = smooth(.72, .9, N2.n(xs * .09, ys * 2.6));
      const low = N.fbm(xs * .0012, ys * .008, 2);
      let t = late * .42 + fib * .3 + low * .38 + pore * .12 + kc * .7 - .2;
      let hh = late * .25 + fib * .2;
      if (style === 'sawn') {
        const a = xs + ys * .18 + N.n(ys * .01, xs * .001) * 50;
        hh += Math.sin(a * .19) * .5 + Math.sin(a * .047 + 1.7) * .3 + N2.n(xs * .22, ys * .22) * .8;
        t += N.n(xs * .02, ys * .3) * .06;
      } else if (style === 'blast') {
        hh = late * 2.4 + fib * .5 + N2.n(xs * .3, ys * .3) * .2;
      } else if (style === 'smooth') {
        hh = fib * .08 + late * .1;
      }
      tone[i] = t; ht[i] = hh;
    }
  }
  if (style === 'hewn') {
    // adze facets: overlapping elliptical scoops, carved with min()
    const carve = new Float32Array(w * h).fill(0);
    const rx0 = 95 / scale, ry0 = 34 / scale;
    const count = Math.round(w * h / (rx0 * ry0 * 1.3));
    for (let k = 0; k < count; k++) {
      const cx = R() * w, cy = R() * h, rx = rx0 * (.7 + R() * .6), ry = ry0 * (.7 + R() * .6), dep = .8 + R() * .8;
      const x0 = Math.max(0, cx - rx | 0), x1 = Math.min(w - 1, cx + rx | 0), y0 = Math.max(0, cy - ry | 0), y1 = Math.min(h - 1, cy + ry | 0);
      for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) {
        const dx = (x - cx) / rx, dy = (y - cy) / ry, q = dx * dx + dy * dy;
        if (q < 1) { const v = dep * (q - 1); const i = y * w + x; if (v < carve[i]) carve[i] = v; }
      }
    }
    const amp = rx0 / 22;
    for (let i = 0; i < w * h; i++) { ht[i] += carve[i] * amp; tone[i] += carve[i] * -.03; }
    // drying checks along the grain
    for (let c = 0; c < w * scale / 380; c++) {
      const x0 = R() * w, len = (140 + R() * 380) / scale, yc = R() * h, ph = R() * 10;
      for (let x = Math.max(0, x0 | 0); x < Math.min(w, x0 + len); x++) {
        const taper = Math.sin(Math.PI * (x - x0) / len), cy = yc + Math.sin((x - x0) * .015 * scale + ph) * 3 / scale;
        const half = 2.4 * taper / Math.sqrt(scale);
        for (let y = Math.max(0, cy - half - 2 | 0); y < Math.min(h, cy + half + 2); y++) {
          const dy = Math.abs(y - cy); if (dy < half) { const i = y * w + x; ht[i] -= 1.5 * (1 - dy / half); tone[i] += 1.1 * (1 - dy / half); }
        }
      }
    }
  }
  // blur heights a touch, then relief-shade (light from upper-left)
  const hb = new Float32Array(w * h);
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    let s = 0, n = 0;
    for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) { const xx = x + dx, yy = y + dy; if (xx >= 0 && yy >= 0 && xx < w && yy < h) { s += ht[yy * w + xx]; n++; } }
    hb[y * w + x] = s / n;
  }
  const shade = new Float32Array(w * h);
  const k = (style === 'smooth' ? .6 : 1.3) * Math.sqrt(scale);
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    const i = y * w + x;
    const dx = hb[y * w + Math.min(w - 1, x + 1)] - hb[y * w + Math.max(0, x - 1)];
    const dy = hb[Math.min(h - 1, y + 1) * w + x] - hb[Math.max(0, y - 1) * w + x];
    shade[i] = clamp(1 + (-dx * .5 - dy * .85) * k * .5, .5, 1.4);
    tone[i] = clamp(tone[i]);
  }
  return { w, h, tone, shade };
}

function tintWood(maps, fin) {
  const cv = document.createElement('canvas'); cv.width = maps.w; cv.height = maps.h;
  const cx = cv.getContext('2d'), img = cx.createImageData(maps.w, maps.h), D = img.data;
  const L = hex(fin.light), Dk = hex(fin.dark);
  const tc = fin.flat ? .35 : 1;
  for (let i = 0; i < maps.tone.length; i++) {
    const t = maps.tone[i] * tc, s = fin.flat ? 1 + (maps.shade[i] - 1) * .7 : maps.shade[i];
    D[i * 4] = clamp((L[0] + (Dk[0] - L[0]) * t) * s, 0, 255);
    D[i * 4 + 1] = clamp((L[1] + (Dk[1] - L[1]) * t) * s, 0, 255);
    D[i * 4 + 2] = clamp((L[2] + (Dk[2] - L[2]) * t) * s, 0, 255);
    D[i * 4 + 3] = 255;
  }
  cx.putImageData(img, 0, 0);
  return cv;
}

// texture bank, generated lazily and cached
const TEX = {};
const MAPS = {};
function wood(style = 'hewn', finish = 'honey', kind = 'beam') {
  const key = `${style}|${finish}|${kind}`;
  if (TEX[key]) return TEX[key];
  const mk = `${style}|${kind}`;
  if (!MAPS[mk]) {
    const seed = { hewn: 11, sawn: 23, blast: 37, smooth: 41 }[style] + (kind === 'macro' ? 100 : 0);
    MAPS[mk] = kind === 'macro' ? woodMaps(style, 1600, 900, seed, .42) : woodMaps(style, 1600, 240, seed, 1);
  }
  return TEX[key] = tintWood(MAPS[mk], [...FINISHES, ...PAINTS].find(f => f.id === finish));
}

// simple procedural floor planks + plaster
function plankTexture(seed = 5) {
  const w = 1024, h = 1024, cv = document.createElement('canvas'); cv.width = w; cv.height = h;
  const cx = cv.getContext('2d');
  const R = rng(seed), base = wood('smooth', 'natural');
  const rows = 8, rh = h / rows;
  for (let r = 0; r < rows; r++) {
    let x = -R() * 400;
    while (x < w) {
      const len = 380 + R() * 420;
      const sx = R() * (base.width - len);
      cx.drawImage(base, sx, R() * 100, len, 120, x, r * rh, len, rh);
      cx.fillStyle = `rgba(${R() < .5 ? '255,235,210' : '40,20,5'},${R() * .12})`;
      cx.fillRect(x, r * rh, len, rh);
      cx.fillStyle = 'rgba(30,15,5,.55)'; cx.fillRect(x, r * rh, 2, rh);
      x += len;
    }
    cx.fillStyle = 'rgba(30,15,5,.5)'; cx.fillRect(0, r * rh, w, 2);
  }
  return cv;
}

// ── tiny 3D renderer (canvas 2D, textured quads, painter's algorithm) ──────
const v3 = {
  add: (a, b) => [a[0] + b[0], a[1] + b[1], a[2] + b[2]],
  sub: (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]],
  mul: (a, s) => [a[0] * s, a[1] * s, a[2] * s],
  dot: (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2],
  cross: (a, b) => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]],
  norm: a => { const l = Math.hypot(a[0], a[1], a[2]) || 1; return [a[0] / l, a[1] / l, a[2] / l]; },
  lerp: (a, b, t) => [lerp(a[0], b[0], t), lerp(a[1], b[1], t), lerp(a[2], b[2], t)],
};

function camera(pos, target, fov = 55, roll = 0) {
  const f = v3.norm(v3.sub(target, pos));
  let r = v3.norm(v3.cross(f, [0, 1, 0]));
  let u = v3.cross(r, f);
  if (roll) { const c = Math.cos(roll), s = Math.sin(roll); [r, u] = [v3.add(v3.mul(r, c), v3.mul(u, s)), v3.add(v3.mul(u, c), v3.mul(r, -s))]; }
  const foc = (H / 2) / Math.tan(fov * Math.PI / 360);
  return {
    pos, f, r, u, foc,
    view: p => { const d = v3.sub(p, pos); return [v3.dot(d, r), v3.dot(d, u), v3.dot(d, f)]; },
    proj: v => [W / 2 + v[0] * foc / v[2], H / 2 - v[1] * foc / v[2]],
  };
}

const NEAR = .05;
function clipNear(poly) { // poly: [{v:[x,y,z], uv:[u,v]}]
  const out = [];
  for (let i = 0; i < poly.length; i++) {
    const a = poly[i], b = poly[(i + 1) % poly.length];
    const ai = a.v[2] >= NEAR, bi = b.v[2] >= NEAR;
    if (ai) out.push(a);
    if (ai !== bi) {
      const t = (NEAR - a.v[2]) / (b.v[2] - a.v[2]);
      out.push({ v: v3.lerp(a.v, b.v, t), uv: [lerp(a.uv[0], b.uv[0], t), lerp(a.uv[1], b.uv[1], t)] });
    }
  }
  return out;
}

function texTri(ctx, img, p0, p1, p2, t0, t1, t2) {
  // expand clip triangle slightly to hide anti-aliasing seams
  const cx = (p0[0] + p1[0] + p2[0]) / 3, cy = (p0[1] + p1[1] + p2[1]) / 3;
  const ex = p => { const dx = p[0] - cx, dy = p[1] - cy, l = Math.hypot(dx, dy) || 1; return [p[0] + dx / l * .9, p[1] + dy / l * .9]; };
  const q0 = ex(p0), q1 = ex(p1), q2 = ex(p2);
  ctx.save();
  ctx.beginPath(); ctx.moveTo(q0[0], q0[1]); ctx.lineTo(q1[0], q1[1]); ctx.lineTo(q2[0], q2[1]); ctx.closePath(); ctx.clip();
  const du1 = t1[0] - t0[0], dv1 = t1[1] - t0[1], du2 = t2[0] - t0[0], dv2 = t2[1] - t0[1];
  const det = du1 * dv2 - du2 * dv1;
  if (Math.abs(det) > 1e-9) {
    const a = ((p1[0] - p0[0]) * dv2 - (p2[0] - p0[0]) * dv1) / det;
    const b = ((p1[1] - p0[1]) * dv2 - (p2[1] - p0[1]) * dv1) / det;
    const c = ((p2[0] - p0[0]) * du1 - (p1[0] - p0[0]) * du2) / det;
    const d = ((p2[1] - p0[1]) * du1 - (p1[1] - p0[1]) * du2) / det;
    ctx.transform(a, b, c, d, p0[0] - a * t0[0] - c * t0[1], p0[1] - b * t0[0] - d * t0[1]);
    ctx.drawImage(img, 0, 0);
  }
  ctx.restore();
}

// Scene graph: a flat list of quads. A quad = 4 world points (p0..p3 winding CCW seen from
// the front), optional texture with uv rect, flat colour otherwise.
function quad(p, opt = {}) { return { p, ...opt }; }

// Axis-aligned box helper. dims along x (length), y (height), z (depth).
// faces: which faces to emit. tex maps the long faces to the wood texture.
function box(c, sx, sy, sz, opt = {}) {
  if (Array.isArray(sx)) { opt = sy || {}; [sx, sy, sz] = sx; }
  const [x, y, z] = c, hx = sx / 2, hy = sy / 2, hz = sz / 2;
  const P = (a, b, d) => [x + a * hx, y + b * hy, z + d * hz];
  const faces = [];
  const along = opt.axis || 'x';
  const tex = opt.tex, tw = tex ? tex.width : 0, th = tex ? tex.height : 0;
  const lenUV = opt.uvLen || 1; // fraction of texture length used
  const u0 = opt.uOff || 0;
  const uvL = (vA, vB) => [[u0 * tw, vA * th], [(u0 + lenUV) * tw, vA * th], [(u0 + lenUV) * tw, vB * th], [u0 * tw, vB * th]];
  const add = (pts, n, kind) => faces.push({ p: pts, n, kind, ...opt, tex: kind === 'end' ? (opt.endTex || null) : tex, uv: kind === 'end' ? null : opt._uv });
  if (along === 'x') {
    add([P(-1, -1, 1), P(1, -1, 1), P(1, 1, 1), P(-1, 1, 1)], [0, 0, 1], 'side');      // +z
    add([P(1, -1, -1), P(-1, -1, -1), P(-1, 1, -1), P(1, 1, -1)], [0, 0, -1], 'side');  // -z
    add([P(-1, -1, -1), P(1, -1, -1), P(1, -1, 1), P(-1, -1, 1)], [0, -1, 0], 'bottom');// -y
    add([P(-1, 1, 1), P(1, 1, 1), P(1, 1, -1), P(-1, 1, -1)], [0, 1, 0], 'top');       // +y
    add([P(-1, -1, -1), P(-1, -1, 1), P(-1, 1, 1), P(-1, 1, -1)], [-1, 0, 0], 'end');
    add([P(1, -1, 1), P(1, -1, -1), P(1, 1, -1), P(1, 1, 1)], [1, 0, 0], 'end');
    faces.forEach((f, i) => { if (f.kind !== 'end') f.uv = uvL(i === 2 ? .05 : .5, i === 2 ? .45 : .95); });
  } else { // along z
    add([P(1, -1, 1), P(1, -1, -1), P(1, 1, -1), P(1, 1, 1)], [1, 0, 0], 'side');
    add([P(-1, -1, -1), P(-1, -1, 1), P(-1, 1, 1), P(-1, 1, -1)], [-1, 0, 0], 'side');
    add([P(-1, -1, 1), P(-1, -1, -1), P(1, -1, -1), P(1, -1, 1)], [0, -1, 0], 'bottom');
    add([P(-1, 1, -1), P(-1, 1, 1), P(1, 1, 1), P(1, 1, -1)], [0, 1, 0], 'top');
    add([P(-1, -1, 1), P(1, -1, 1), P(1, 1, 1), P(-1, 1, 1)], [0, 0, 1], 'end');
    add([P(1, -1, -1), P(-1, -1, -1), P(-1, 1, -1), P(1, 1, -1)], [0, 0, -1], 'end');
    faces.forEach((f, i) => { if (f.kind !== 'end') f.uv = uvL(i === 2 ? .05 : .5, i === 2 ? .45 : .95); });
  }
  return faces.filter(f => !opt.skip || !opt.skip.includes(f.kind));
}

// a beam = textured box along an axis, cut into chunks so depth sorting stays correct
function beam(c, len, wdt, hgt, style, finish, axis = 'x', extra = {}) {
  const tex = wood(style, finish);
  const n = Math.max(1, Math.ceil(len / (extra.chunk || 1.1)));
  const span = Math.min(1, len / 6.5), u0 = Math.min(extra.uOff || 0, 1 - span);
  const out = [];
  for (let i = 0; i < n; i++) {
    const a = -len / 2 + len * i / n, b = -len / 2 + len * (i + 1) / n, mid = (a + b) / 2;
    const cc = axis === 'x' ? [c[0] + mid, c[1], c[2]] : [c[0], c[1], c[2] + mid];
    const sx = axis === 'x' ? len / n : wdt, sz = axis === 'x' ? wdt : len / n;
    const skip = ['top', ...(extra.skip || [])];
    const faces = box(cc, sx, hgt, sz, { ...extra, tex, axis, color: FINISHES.find(f => f.id === finish).dark, uvLen: span / n, uOff: u0 + span * i / n, skip });
    // drop interior end caps
    out.push(...faces.filter(f => f.kind !== 'end' || (i === 0 && isFirstEnd(f, axis)) || (i === n - 1 && !isFirstEnd(f, axis))));
    for (const f of faces) if (f.kind !== 'end') f.segs = 3;
  }
  return out;
}
const isFirstEnd = (f, axis) => axis === 'x' ? f.n[0] < 0 : f.n[2] > 0;

// plane subdivided into cells so it can carry soft lighting
function plane(p0, p1, p3, color, nx = 10, ny = 10, opt = {}) {
  // p0 origin, p1 along "u", p3 along "v"
  const du = v3.sub(p1, p0), dv = v3.sub(p3, p0);
  const n = v3.norm(v3.cross(du, dv));
  const out = [];
  for (let j = 0; j < ny; j++) for (let i = 0; i < nx; i++) {
    const a = v3.add(p0, v3.add(v3.mul(du, i / nx), v3.mul(dv, j / ny)));
    const b = v3.add(p0, v3.add(v3.mul(du, (i + 1) / nx), v3.mul(dv, j / ny)));
    const c = v3.add(p0, v3.add(v3.mul(du, (i + 1) / nx), v3.mul(dv, (j + 1) / ny)));
    const d = v3.add(p0, v3.add(v3.mul(du, i / nx), v3.mul(dv, (j + 1) / ny)));
    const f = { p: [a, b, c, d], n, color, cell: true, ...opt };
    if (opt.tex) { const tw = opt.tex.width * (opt.rep || 1), th = opt.tex.height * (opt.rep || 1); f.uv = [[i / nx * tw, j / ny * th], [(i + 1) / nx * tw, j / ny * th], [(i + 1) / nx * tw, (j + 1) / ny * th], [i / nx * tw, (j + 1) / ny * th]]; }
    out.push(f);
  }
  return out;
}

// lighting: ambient + one sun direction + point lights with falloff
function lightAt(pt, n, L) {
  let l = L.ambient;
  const sd = v3.dot(n, L.sun); if (sd > 0) l += sd * L.sunI;
  for (const pl of L.points || []) {
    const d = v3.sub(pl.p, pt), dist = Math.hypot(d[0], d[1], d[2]);
    const nd = Math.max(0, v3.dot(n, v3.mul(d, 1 / dist)));
    l += nd * pl.i / (1 + dist * dist * pl.k);
  }
  return l;
}
const tm = l => l <= .85 ? l : .85 + (1 - Math.exp(-(l - .85) * 2.2)) * .3;

function render3D(ctx, faces, cam, L) {
  const list = [];
  for (const f of faces) {
    const ctr = v3.mul(f.p.reduce((s, p) => v3.add(s, p), [0, 0, 0]), .25);
    if (!f.double && v3.dot(f.n, v3.sub(cam.pos, ctr)) <= 0) continue;
    const vs = f.p.map(cam.view);
    if (vs.every(v => v[2] < NEAR)) continue;
    const z = vs.reduce((s, v) => s + v[2], 0) / 4;
    list.push({ f, vs, z: f.bias ? z + f.bias : z, ctr });
  }
  list.sort((a, b) => b.z - a.z);
  const tint = hex(L.tint || '#ffffff');
  for (const { f, vs, ctr } of list) {
    const base = hex(f.color || '#888888');
    if (f.tex && f.uv) {
      // perspective-correct enough: subdivide along the long edge
      const segs = f.segs || (f.cell ? 1 : 14);
      for (let s = 0; s < segs; s++) {
        const t0 = s / segs, t1 = (s + 1) / segs;
        const A = v3.lerp(vs[0], vs[1], t0), B = v3.lerp(vs[0], vs[1], t1), Cc = v3.lerp(vs[3], vs[2], t1), D = v3.lerp(vs[3], vs[2], t0);
        const uvA = [lerp(f.uv[0][0], f.uv[1][0], t0), lerp(f.uv[0][1], f.uv[1][1], t0)];
        const uvB = [lerp(f.uv[0][0], f.uv[1][0], t1), lerp(f.uv[0][1], f.uv[1][1], t1)];
        const uvC = [lerp(f.uv[3][0], f.uv[2][0], t1), lerp(f.uv[3][1], f.uv[2][1], t1)];
        const uvD = [lerp(f.uv[3][0], f.uv[2][0], t0), lerp(f.uv[3][1], f.uv[2][1], t0)];
        const poly = clipNear([{ v: A, uv: uvA }, { v: B, uv: uvB }, { v: Cc, uv: uvC }, { v: D, uv: uvD }]);
        if (poly.length < 3) continue;
        const pp = poly.map(q => cam.proj(q.v));
        for (let k = 1; k < poly.length - 1; k++) texTri(ctx, f.tex, pp[0], pp[k], pp[k + 1], poly[0].uv, poly[k].uv, poly[k + 1].uv);
      }
      // lighting overlay as a screen-space gradient along the face
      const poly = clipNear(vs.map((v, i) => ({ v, uv: [0, 0] })));
      if (poly.length < 3) continue;
      const pp = poly.map(q => cam.proj(q.v));
      const wa = v3.lerp(f.p[0], f.p[3], .5), wb = v3.lerp(f.p[1], f.p[2], .5);
      const va = cam.view(wa), vb = cam.view(wb);
      let g = null;
      if (va[2] > NEAR && vb[2] > NEAR) {
        const sa = cam.proj(va), sb = cam.proj(vb);
        const dx = sb[0] - sa[0], dy = sb[1] - sa[1], L2 = dx * dx + dy * dy;
        if (L2 > 4) {
          g = ctx.createLinearGradient(sa[0], sa[1], sb[0], sb[1]);
          for (let i = 0; i <= 6; i++) {
            const wp = v3.lerp(wa, wb, i / 6), vp = cam.view(wp), sp = cam.proj(vp);
            const o = clamp(((sp[0] - sa[0]) * dx + (sp[1] - sa[1]) * dy) / L2);
            const l = tm(lightAt(wp, f.n, L) * (f.lum || 1));
            g.addColorStop(o, l < 1 ? `rgba(12,7,3,${clamp(1 - l)})` : `rgba(255,236,205,${clamp((l - 1) * .5, 0, .5)})`);
          }
        }
      }
      ctx.beginPath(); pp.forEach((p, i) => i ? ctx.lineTo(p[0], p[1]) : ctx.moveTo(p[0], p[1])); ctx.closePath();
      const l = tm(lightAt(ctr, f.n, L) * (f.lum || 1));
      ctx.fillStyle = g || (l < 1 ? `rgba(12,7,3,${clamp(1 - l)})` : `rgba(255,236,205,${clamp((l - 1) * .5, 0, .5)})`);
      ctx.fill();
    } else {
      const poly = clipNear(vs.map(v => ({ v, uv: [0, 0] })));
      if (poly.length < 3) continue;
      const pp = poly.map(q => cam.proj(q.v));
      ctx.beginPath(); pp.forEach((p, i) => i ? ctx.lineTo(p[0], p[1]) : ctx.moveTo(p[0], p[1])); ctx.closePath();
      const col = l => { const k = tm(l * (f.lum || 1)); return rgba([base[0] * k * tint[0] / 255, base[1] * k * tint[1] / 255, base[2] * k * tint[2] / 255], f.alpha ?? 1); };
      if (f.emit) {
        ctx.save(); ctx.fillStyle = f.color; if (f.bloom) { ctx.shadowColor = f.bloom; ctx.shadowBlur = f.bloomR || 80; } ctx.fill(); ctx.fill(); ctx.restore();
      } else if (f.cell && vs.every(v => v[2] > NEAR)) {
        // fit a linear luminance ramp across the cell in screen space (smooth shading)
        const Ls = f.p.map(p => lightAt(p, f.n, L)), S = f.p.map(p => cam.proj(cam.view(p)));
        const mx = S.reduce((a, p) => a + p[0], 0) / 4, my = S.reduce((a, p) => a + p[1], 0) / 4, ml = Ls.reduce((a, b) => a + b, 0) / 4;
        let sxx = 0, sxy = 0, syy = 0, sxl = 0, syl = 0;
        for (let i = 0; i < 4; i++) { const dx = S[i][0] - mx, dy = S[i][1] - my, dl = Ls[i] - ml; sxx += dx * dx; sxy += dx * dy; syy += dy * dy; sxl += dx * dl; syl += dy * dl; }
        const det = sxx * syy - sxy * sxy;
        let gx = 0, gy = 0; if (Math.abs(det) > 1e-6) { gx = (sxl * syy - syl * sxy) / det; gy = (syl * sxx - sxl * sxy) / det; }
        const gl = Math.hypot(gx, gy);
        if (gl > 1e-7) {
          const ux = gx / gl, uy = gy / gl, r = Math.max(...S.map(p => Math.abs((p[0] - mx) * ux + (p[1] - my) * uy))) + 2;
          const g = ctx.createLinearGradient(mx - ux * r, my - uy * r, mx + ux * r, my + uy * r);
          g.addColorStop(0, col(ml - gl * r)); g.addColorStop(1, col(ml + gl * r));
          ctx.fillStyle = g; ctx.strokeStyle = g;
        } else { ctx.fillStyle = ctx.strokeStyle = col(ml); }
        ctx.fill(); ctx.lineWidth = 1.2; ctx.stroke();
      } else {
        const c = col(lightAt(ctr, f.n, L));
        ctx.fillStyle = c; ctx.fill();
        if (f.cell) { ctx.strokeStyle = c; ctx.lineWidth = 1.2; ctx.stroke(); }
      }
    }
  }
}

// ── canvas helpers ──────────────────────────────────────────────────────────
function roundRect(ctx, x, y, w, h, r) { ctx.beginPath(); ctx.roundRect(x, y, w, h, r); }
function withAlpha(ctx, a, fn) { ctx.save(); ctx.globalAlpha *= a; fn(); ctx.restore(); }

// text with tracking, returns width
function tw(ctx, s, f, track = 0) { ctx.font = f; ctx.letterSpacing = track + 'px'; const w = ctx.measureText(s).width; ctx.letterSpacing = '0px'; return w; }
function text(ctx, s, x, y, f, color, align = 'left', track = 0, alpha = 1) {
  ctx.save(); ctx.font = f; ctx.letterSpacing = track + 'px'; ctx.fillStyle = color; ctx.globalAlpha *= alpha;
  ctx.textAlign = align; ctx.textBaseline = 'alphabetic'; ctx.fillText(s, x, y); ctx.restore();
}

// masked line reveal: the line rises out of an invisible slot
function slotText(ctx, s, x, y, p, f, color, align = 'left', track = 0, size = 100) {
  const w = tw(ctx, s, f, track);
  const x0 = align === 'center' ? x - w / 2 : align === 'right' ? x - w : x;
  ctx.save();
  ctx.beginPath(); ctx.rect(x0 - 20, y - size * 1.05, w + 40, size * 1.35); ctx.clip();
  text(ctx, s, x, y + (1 - p) * size * 1.3, f, color, align, track);
  ctx.restore();
}

// per-character stagger (slide + fade + slight blur-free scale)
function staggerText(ctx, s, x, y, t, f, color, o = {}) {
  const track = o.track || 0, st = o.stagger ?? .03, d = o.dur ?? .6, ease = o.ease || E.outExpo;
  const total = tw(ctx, s, f, track);
  let cx = o.align === 'center' ? x - total / 2 : o.align === 'right' ? x - total : x;
  ctx.save(); ctx.font = f; ctx.fillStyle = color; ctx.textBaseline = 'alphabetic';
  const order = o.fromCenter ? [...s].map((_, i) => Math.abs(i - (s.length - 1) / 2)) : [...s].map((_, i) => i);
  [...s].forEach((ch, i) => {
    const cw = tw(ctx, ch, f, 0) + track;
    const p = ease(clamp((t - order[i] * st) / d));
    if (p > 0) {
      ctx.save(); ctx.font = f; ctx.globalAlpha *= clamp(p * 1.6);
      ctx.translate(cx + cw / 2, y + (1 - p) * (o.dy ?? 40));
      const sc = o.scale ? lerp(o.scale, 1, p) : 1; ctx.scale(sc, sc);
      ctx.textAlign = 'center'; ctx.fillStyle = color; ctx.fillText(ch, -track / 2, 0); ctx.restore();
    }
    cx += cw;
  });
  ctx.restore();
  return total;
}

// wrap text into lines
function wrap(ctx, s, f, maxW) {
  ctx.font = f; const words = s.split(' '), lines = []; let cur = '';
  for (const w of words) { const t = cur ? cur + ' ' + w : w; if (ctx.measureText(t).width > maxW && cur) { lines.push(cur); cur = w; } else cur = t; }
  if (cur) lines.push(cur); return lines;
}

// animated stroke along a polyline
function drawPath(ctx, pts, p, color, lw = 3) {
  if (p <= 0) return;
  let total = 0; const seglen = [];
  for (let i = 1; i < pts.length; i++) { const l = Math.hypot(pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]); seglen.push(l); total += l; }
  let rem = total * p;
  ctx.save(); ctx.strokeStyle = color; ctx.lineWidth = lw; ctx.lineCap = 'round'; ctx.lineJoin = 'round';
  ctx.beginPath(); ctx.moveTo(pts[0][0], pts[0][1]);
  for (let i = 1; i < pts.length && rem > 0; i++) {
    const l = seglen[i - 1], k = Math.min(1, rem / l);
    ctx.lineTo(lerp(pts[i - 1][0], pts[i][0], k), lerp(pts[i - 1][1], pts[i][1], k)); rem -= l;
  }
  ctx.stroke(); ctx.restore();
}

// dimension line with ticks + label
function dimLine(ctx, x0, y0, x1, y1, p, label, color = C.accent2) {
  const mx = lerp(x0, x1, .5), my = lerp(y0, y1, .5);
  const a = lerp(mx, x0, p), b = lerp(my, y0, p), c = lerp(mx, x1, p), d = lerp(my, y1, p);
  ctx.save(); ctx.strokeStyle = color; ctx.lineWidth = 2.5;
  ctx.beginPath(); ctx.moveTo(a, b); ctx.lineTo(c, d); ctx.stroke();
  const nx = -(y1 - y0), ny = x1 - x0, nl = Math.hypot(nx, ny) || 1;
  for (const [px, py] of [[a, b], [c, d]]) { ctx.beginPath(); ctx.moveTo(px + nx / nl * 14, py + ny / nl * 14); ctx.lineTo(px - nx / nl * 14, py - ny / nl * 14); ctx.stroke(); }
  if (label && p > .5) {
    const al = inv(.5, 1, p);
    ctx.font = font('bold', 28); const w = ctx.measureText(label).width + 28;
    ctx.globalAlpha = al; ctx.fillStyle = C.ink; roundRect(ctx, mx - w / 2, my - 24, w, 48, 24); ctx.fill();
    ctx.strokeStyle = color; ctx.lineWidth = 2; ctx.stroke();
    text(ctx, label, mx, my + 10, font('bold', 28), color, 'center', 1);
  }
  ctx.restore();
}

// ── post effects ────────────────────────────────────────────────────────────
let _vig, _grain = [];
function post(ctx, t, o = {}) {
  if (!_vig) {
    _vig = document.createElement('canvas'); _vig.width = W; _vig.height = H;
    const v = _vig.getContext('2d'), g = v.createRadialGradient(W / 2, H / 2, H * .35, W / 2, H / 2, H * 1.05);
    g.addColorStop(0, 'rgba(0,0,0,0)'); g.addColorStop(1, 'rgba(8,5,2,.62)'); v.fillStyle = g; v.fillRect(0, 0, W, H);
    for (let k = 0; k < 6; k++) {
      const c = document.createElement('canvas'); c.width = 480; c.height = 270;
      const x = c.getContext('2d'), im = x.createImageData(480, 270), R = rng(900 + k);
      for (let i = 0; i < im.data.length; i += 4) { const g = R() * 255; im.data[i] = im.data[i + 1] = im.data[i + 2] = g; im.data[i + 3] = 255; }
      x.putImageData(im, 0, 0); _grain.push(c);
    }
  }
  ctx.save();
  ctx.globalAlpha = o.vignette ?? 1; ctx.drawImage(_vig, 0, 0);
  ctx.globalAlpha = o.grain ?? .045; ctx.globalCompositeOperation = 'overlay';
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(_grain[Math.floor(t * FPS) % 6], 0, 0, W, H);
  ctx.restore();
}

// ── timeline ────────────────────────────────────────────────────────────────
// shots: [{d, draw(ctx,t,shot), label}] played back to back. Returns lookup fn.
function timeline(shots) {
  let acc = 0; for (const s of shots) { s.t0 = acc; acc += s.d; }
  return {
    shots, duration: acc,
    at(T) { for (const s of shots) if (T >= s.t0 && T < s.t0 + s.d) return s; return shots[shots.length - 1]; },
  };
}
